/// Build script: generate `casefold_data.rs` and `general_category_data.rs` in `$OUT_DIR`.
///
/// ## CaseFolding.txt
///
/// Reads `data/CaseFolding.txt` (Unicode 17.0.0, committed to the repository)
/// and emits two static arrays:
///
/// - `SIMPLE_CASE_FOLDS`: all non-trivial single-codepoint case folds (status
///   `C`), sorted by source codepoint.
/// - `MULTI_CASE_FOLDS`: all multi-codepoint case folds (status `F`), sorted
///   by source codepoint.
///
/// Status `S` (simple-only, differs from full) and `T` (Turkish) entries are
/// ignored because the engine implements *full* Unicode case folding.
///
/// ## DerivedGeneralCategory.txt
///
/// Reads `data/extracted/DerivedGeneralCategory.txt` and emits a compact
/// sorted range table:
///
/// - `GC_RANGES`: `&[(u32, u32, u8)]` — `(lo, hi, category_id)` sorted by `lo`.
///
/// The `u8` category IDs are defined as `GC_*` constants in the same file and
/// correspond to the 30 Unicode General Category values.
///
/// To update the data files, run:
///   sh scripts/fetch_unicode_data.sh [VERSION]
///
/// Re-run automatically by Cargo when `build.rs` or the data files change.
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("casefold_data.rs");

    let src =
        fs::read_to_string("data/CaseFolding.txt").expect("data/CaseFolding.txt not found; run: sh scripts/fetch_unicode_data.sh");

    let mut simple: Vec<(u32, u32)> = Vec::new();
    let mut multi: Vec<(u32, Vec<u32>)> = Vec::new();

    for line in src.lines() {
        // Strip trailing comment and whitespace.
        let line = if let Some(pos) = line.find('#') {
            &line[..pos]
        } else {
            line
        }
        .trim();

        if line.is_empty() {
            continue;
        }

        let mut fields = line.split(';');
        let src_hex = fields.next().unwrap_or("").trim();
        let status = fields.next().unwrap_or("").trim();
        let mapping = fields.next().unwrap_or("").trim();

        // Only process C (common single-char) and F (full multi-char) entries.
        if status != "C" && status != "F" {
            continue;
        }

        let src_cp = u32::from_str_radix(src_hex, 16)
            .unwrap_or_else(|_| panic!("invalid codepoint: {src_hex}"));

        let targets: Vec<u32> = mapping
            .split_whitespace()
            .map(|h| {
                u32::from_str_radix(h, 16)
                    .unwrap_or_else(|_| panic!("invalid mapping codepoint: {h}"))
            })
            .collect();

        match targets.len() {
            0 => {}
            1 => simple.push((src_cp, targets[0])),
            _ => multi.push((src_cp, targets)),
        }
    }

    // Both tables arrive already sorted by source codepoint (CaseFolding.txt
    // is in ascending order), but sort explicitly for safety.
    simple.sort_unstable_by_key(|&(src, _)| src);
    multi.sort_unstable_by_key(|&(src, _)| src);

    let mut out = String::with_capacity(128 * 1024);

    out.push_str(
        "/// All non-trivial single-codepoint Unicode case folds: `(src, folded)`,\n\
         /// sorted by source codepoint.  Derived from data/CaseFolding.txt (status C).\n\
         /// Generated by `build.rs`; do not edit directly.\n\
         pub const SIMPLE_CASE_FOLDS: &[(char, char)] = &[\n",
    );
    for &(src, dst) in &simple {
        let src_ch = char::from_u32(src).unwrap();
        let dst_ch = char::from_u32(dst).unwrap();
        out.push_str(&format!(
            "    ('\\u{{{src:04X}}}', '\\u{{{dst:04X}}}'),  // {src_ch} -> {dst_ch}\n"
        ));
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// All Unicode multi-codepoint case folds: `(src, &[folded_chars])`,\n\
         /// sorted by source codepoint.  Derived from data/CaseFolding.txt (status F).\n\
         /// Generated by `build.rs`; do not edit directly.\n\
         pub const MULTI_CASE_FOLDS: &[(char, &[char])] = &[\n",
    );
    for (src, fold) in &multi {
        let src_ch = char::from_u32(*src).unwrap();
        let fold_str: String = fold
            .iter()
            .map(|&c| format!("'\\u{{{c:04X}}}'"))
            .collect::<Vec<_>>()
            .join(", ");
        let fold_display: String = fold
            .iter()
            .map(|&c| char::from_u32(c).unwrap())
            .collect();
        out.push_str(&format!(
            "    ('\\u{{{src:04X}}}', &[{fold_str}]),  // {src_ch} -> {fold_display}\n"
        ));
    }
    out.push_str("];\n");

    fs::write(&dest, out).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data/CaseFolding.txt");

    gen_general_category(&out_dir);
}

fn gen_general_category(out_dir: &str) {
    let dest = Path::new(out_dir).join("general_category_data.rs");

    let src = fs::read_to_string("data/extracted/DerivedGeneralCategory.txt")
        .expect("data/extracted/DerivedGeneralCategory.txt not found; run: sh scripts/fetch_unicode_data.sh");

    // Canonical two-letter category codes in alphabetical order.
    // The index in this array is the u8 ID used in GC_RANGES.
    const GC_NAMES: &[&str] = &[
        "Cc", "Cf", "Cn", "Co", "Cs", // C*
        "Ll", "Lm", "Lo", "Lt", "Lu", // L*
        "Mc", "Me", "Mn",             // M*
        "Nd", "Nl", "No",             // N*
        "Pc", "Pd", "Pe", "Pf", "Pi", "Po", "Ps", // P*
        "Sc", "Sk", "Sm", "So",       // S*
        "Zl", "Zp", "Zs",             // Z*
    ];

    let gc_id = |code: &str| -> u8 {
        GC_NAMES
            .iter()
            .position(|&n| n == code)
            .unwrap_or_else(|| panic!("unknown GC code: {code}")) as u8
    };

    let mut ranges: Vec<(u32, u32, u8)> = Vec::new();

    for line in src.lines() {
        let line = if let Some(pos) = line.find('#') {
            &line[..pos]
        } else {
            line
        }
        .trim();
        if line.is_empty() {
            continue;
        }

        let mut fields = line.split(';');
        let range_part = fields.next().unwrap_or("").trim();
        let cat_part = fields.next().unwrap_or("").trim();
        if cat_part.is_empty() {
            continue;
        }

        let (lo, hi) = if let Some((a, b)) = range_part.split_once("..") {
            (
                u32::from_str_radix(a.trim(), 16).unwrap_or_else(|_| panic!("bad cp: {a}")),
                u32::from_str_radix(b.trim(), 16).unwrap_or_else(|_| panic!("bad cp: {b}")),
            )
        } else {
            let cp = u32::from_str_radix(range_part, 16)
                .unwrap_or_else(|_| panic!("bad cp: {range_part}"));
            (cp, cp)
        };

        ranges.push((lo, hi, gc_id(cat_part)));
    }

    ranges.sort_unstable_by_key(|&(lo, _, _)| lo);

    // Merge adjacent same-category ranges.
    let mut merged: Vec<(u32, u32, u8)> = Vec::with_capacity(ranges.len());
    for (lo, hi, cat) in ranges {
        if let Some(last) = merged.last_mut()
            && last.2 == cat
            && last.1 + 1 == lo
        {
            last.1 = hi;
            continue;
        }
        merged.push((lo, hi, cat));
    }

    // --- generate the source file ---
    let mut out = String::with_capacity(512 * 1024);

    out.push_str(
        "/// Unicode General Category ID constants (index into GC_RANGES category field).\n\
         /// Generated by `build.rs` from data/extracted/DerivedGeneralCategory.txt.\n\
         #[allow(dead_code)]\n",
    );
    for (i, &name) in GC_NAMES.iter().enumerate() {
        out.push_str(&format!("pub const GC_{}: u8 = {};\n", name.to_uppercase(), i));
    }
    out.push('\n');

    out.push_str(
        "/// Sorted Unicode General Category range table: `(lo, hi, category_id)`.\n\
         /// Generated by `build.rs` from data/extracted/DerivedGeneralCategory.txt.\n\
         pub const GC_RANGES: &[(u32, u32, u8)] = &[\n",
    );
    for (lo, hi, cat) in &merged {
        out.push_str(&format!("    ({lo:#07X}, {hi:#07X}, {cat}),\n"));
    }
    out.push_str("];\n");

    fs::write(&dest, out).unwrap();

    println!("cargo:rerun-if-changed=data/extracted/DerivedGeneralCategory.txt");
}
