/// Build script: generate `casefold_data.rs` in `$OUT_DIR`.
///
/// The generated file contains two static arrays derived from the
/// `unicode-casefold` crate:
///
/// - `SIMPLE_CASE_FOLDS`: all non-trivial single-codepoint case folds,
///   sorted by source codepoint.
/// - `MULTI_CASE_FOLDS`: all multi-codepoint case folds, sorted by source
///   codepoint.
///
/// These tables let `casefold_trie.rs` enumerate case-equivalent codepoints
/// in O(table_size) ≈ O(1 400) rather than the O(1.1 M) full-codepoint scan.
///
/// Re-run automatically by Cargo when `build.rs` itself changes.
use std::env;
use std::fs;
use std::path::Path;

use unicode_casefold::UnicodeCaseFold;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("casefold_data.rs");

    let mut simple: Vec<(char, char)> = Vec::new();
    let mut multi: Vec<(char, Vec<char>)> = Vec::new();

    for cp in 0u32..=0x10_FFFF {
        let Some(ch) = char::from_u32(cp) else {
            continue;
        };
        let fold: Vec<char> = ch.case_fold().collect();
        match fold.len() {
            0 => {}
            1 if fold[0] == ch => {} // identity — skip
            1 => simple.push((ch, fold[0])),
            _ => multi.push((ch, fold)),
        }
    }

    let mut out = String::with_capacity(64 * 1024);

    out.push_str(
        "/// All non-trivial single-codepoint Unicode case folds: `(src, folded)`,\n\
         /// sorted by source codepoint.\n\
         /// Generated by `build.rs`; do not edit directly.\n\
         pub const SIMPLE_CASE_FOLDS: &[(char, char)] = &[\n",
    );
    for (src, dst) in &simple {
        let src_u = *src as u32;
        let dst_u = *dst as u32;
        out.push_str(&format!(
            "    ('\\u{{{src_u:04X}}}', '\\u{{{dst_u:04X}}}'),  // {src} -> {dst}\n"
        ));
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// All Unicode multi-codepoint case folds: `(src, &[folded_chars])`,\n\
         /// sorted by source codepoint.\n\
         /// Generated by `build.rs`; do not edit directly.\n\
         pub const MULTI_CASE_FOLDS: &[(char, &[char])] = &[\n",
    );
    for (src, fold) in &multi {
        let src_u = *src as u32;
        let fold_str: String = fold
            .iter()
            .map(|&c| format!("'\\u{{{:04X}}}'", c as u32))
            .collect::<Vec<_>>()
            .join(", ");
        let fold_display: String = fold.iter().collect();
        out.push_str(&format!(
            "    ('\\u{{{src_u:04X}}}', &[{fold_str}]),  // {src} -> {fold_display}\n"
        ));
    }
    out.push_str("];\n");

    fs::write(&dest, out).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}
