/// Compile-time case-fold expansion utilities.
///
/// `fold_seq_to_trie` builds a [`ByteTrie`] containing every UTF-8 byte
/// sequence that Unicode-case-folds **to** the given target sequence.
/// At match time the engine just walks the trie over raw bytes — no
/// `case_fold()` calls, no UTF-8 decoding.
///
/// `charset_to_bytetrie` builds a [`ByteTrie`] from a `CharSet` by enumerating
/// the charset's compiled inversion-list ranges and inserting multi-codepoint
/// case-fold sequences.  Single-codepoint case equivalents are already in
/// `cs.ranges` and are handled by `CharSet::matches`; the ByteTrie only needs
/// to cover multi-codepoint folds (e.g. ß → "ss").
///
/// # Algorithm
///
/// Both functions use the static [`SIMPLE_CASE_FOLDS`] and
/// [`MULTI_CASE_FOLDS`] tables (generated by `scripts/gen_unicode_tables`)
/// instead of scanning all 1.1 M Unicode codepoints at runtime.  Each table
/// has ≈ 1 400 entries — a >700× reduction over the full-codepoint scan.
///
/// For a target sequence `T = [c0, c1, …, cn]` we recursively find all
/// Unicode codepoints `ch` such that `ch.case_fold()` produces some
/// non-empty prefix `T[0..k]`, then recurse on `T[k..]`.  The base case
/// (empty target) inserts the accumulated byte sequence into the output trie.
use crate::bytetrie::ByteTrie;
use crate::vm::CharSet;

use crate::data::casefold_data::{MULTI_CASE_FOLDS, SIMPLE_CASE_FOLDS};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Build a `ByteTrie` containing all UTF-8 byte sequences whose Unicode case
/// fold equals `target`.
///
/// For example, `fold_seq_to_trie(&['s'])` produces a trie accepting
/// `"s"`, `"S"`, `"ſ"` (U+017F), `"ẛ"` (U+1E9B) etc.
///
/// `fold_seq_to_trie(&['s', 's'])` produces a trie accepting `"ss"`, `"sS"`,
/// `"Ss"`, `"SS"`, `"ß"` (U+00DF), combinations with ſ, etc.
pub fn fold_seq_to_trie(target: &[char]) -> ByteTrie {
    let mut trie = ByteTrie::new();
    let mut buf = Vec::new();
    enumerate_inputs(target, &mut buf, &mut trie);
    trie
}

/// Build a *reversed* `ByteTrie` for backward matching (used by
/// `Inst::FoldSeqBack`).
pub fn fold_seq_to_trie_back(target: &[char]) -> ByteTrie {
    fold_seq_to_trie(target).reversed()
}

// ---------------------------------------------------------------------------
// Internal enumeration
// ---------------------------------------------------------------------------

/// Recursively enumerate all input byte sequences that fold to `remaining`,
/// appending discovered bytes to `buf` and inserting complete sequences into
/// `out`.
fn enumerate_inputs(remaining: &[char], buf: &mut Vec<u8>, out: &mut ByteTrie) {
    if remaining.is_empty() {
        out.insert(buf);
        return;
    }

    // Try every split length k (1..=remaining.len()):
    // find all codepoints whose case_fold == remaining[..k], then recurse.
    for k in 1..=remaining.len() {
        let prefix = &remaining[..k];
        let suffix = &remaining[k..];

        for ch in codepoints_with_fold(prefix) {
            let start = buf.len();
            let mut tmp = [0u8; 4];
            let encoded = ch.encode_utf8(&mut tmp);
            buf.extend_from_slice(encoded.as_bytes());
            enumerate_inputs(suffix, buf, out);
            buf.truncate(start);
        }
    }
}

/// Return the simple (single-codepoint) case fold of `ch` using the static
/// table, or `ch` itself if `ch` is a fold fixed-point.
fn simple_fold(ch: char) -> char {
    match SIMPLE_CASE_FOLDS.binary_search_by_key(&ch, |&(s, _)| s) {
        Ok(i) => SIMPLE_CASE_FOLDS[i].1,
        Err(_) => ch,
    }
}

/// Yield all Unicode codepoints whose full case fold equals `target`.
///
/// Uses the static [`SIMPLE_CASE_FOLDS`] / [`MULTI_CASE_FOLDS`] tables
/// instead of scanning 1.1 M codepoints.
fn codepoints_with_fold(target: &[char]) -> Vec<char> {
    if target.len() == 1 {
        let t = target[0];
        let mut result = Vec::new();
        // t itself if it is a fixed point (simple_fold(t) == t).
        if simple_fold(t) == t {
            result.push(t);
        }
        // All src where SIMPLE_CASE_FOLDS[src] == t.
        for &(src, dst) in SIMPLE_CASE_FOLDS {
            if dst == t {
                result.push(src);
            }
        }
        result
    } else {
        // Multi-codepoint target: search MULTI_CASE_FOLDS.
        MULTI_CASE_FOLDS
            .iter()
            .filter(|&&(_, fold)| fold == target)
            .map(|&(src, _)| src)
            .collect()
    }
}

// ---------------------------------------------------------------------------
// CharSet → ByteTrie
// ---------------------------------------------------------------------------

/// Build a `ByteTrie` for a case-insensitive `Class` instruction.
///
/// For each codepoint in `cs.ranges` that has a multi-codepoint full case fold
/// (e.g. ß → "ss"), all UTF-8 byte sequences that Unicode-case-fold to that
/// same fold sequence are inserted into the trie.  Single-codepoint case
/// equivalents are already in `cs.ranges` and do not need to appear in the
/// trie; `CharSet::matches` handles them via binary search.
///
/// The trie is built from the **non-negated inner ranges** (`cs.ranges`), so
/// it can be used both as a positive advancer (non-negated charset) and as a
/// rejection guard (negated charset).
pub fn charset_to_bytetrie(cs: &CharSet, _ignore_case: bool) -> ByteTrie {
    let mut trie = ByteTrie::new();
    for &(src, fold_seq) in MULTI_CASE_FOLDS {
        if char_in_cs_ranges(src, &cs.ranges) {
            insert_multi_fold_seqs_raw(&mut trie, fold_seq);
        }
    }
    trie
}

/// Insert all byte sequences that Unicode-case-fold to `fold_seq` into `trie`.
fn insert_multi_fold_seqs_raw(trie: &mut ByteTrie, fold_seq: &[char]) {
    let mut buf: Vec<u8> = Vec::new();
    enumerate_inputs(fold_seq, &mut buf, trie);
}

/// Build a reversed `ByteTrie` from a `CharSet` (for backward `ClassBack`).
pub fn charset_to_bytetrie_back(cs: &CharSet, ignore_case: bool) -> ByteTrie {
    charset_to_bytetrie(cs, ignore_case).reversed()
}

fn char_in_cs_ranges(ch: char, ranges: &[(char, char)]) -> bool {
    ranges
        .binary_search_by(|&(lo, hi)| {
            if ch < lo {
                std::cmp::Ordering::Greater
            } else if ch > hi {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn accepts(trie: &ByteTrie, s: &str) -> bool {
        trie.advance(s.as_bytes(), 0) == Some(s.len())
    }

    // --- Single-codepoint folds ---

    #[test]
    fn fold_trie_ascii_s() {
        let t = fold_seq_to_trie(&['s']);
        assert!(accepts(&t, "s"), "s");
        assert!(accepts(&t, "S"), "S");
        assert!(accepts(&t, "ſ"), "ſ U+017F"); // Latin small letter long s (folds to 's')
        assert!(!accepts(&t, "ẛ"), "ẛ U+1E9B folds to ṡ, not s");
        assert!(!accepts(&t, "x"), "x should not match");
        assert!(!accepts(&t, "ß"), "ß has 2-char fold ss, not s");
    }

    #[test]
    fn fold_trie_kelvin() {
        let t = fold_seq_to_trie(&['k']);
        assert!(accepts(&t, "k"), "k");
        assert!(accepts(&t, "K"), "K");
        assert!(accepts(&t, "\u{212A}"), "Kelvin sign U+212A");
        assert!(!accepts(&t, "x"), "x");
    }

    #[test]
    fn fold_trie_ascii_a() {
        let t = fold_seq_to_trie(&['a']);
        assert!(accepts(&t, "a"), "a");
        assert!(accepts(&t, "A"), "A");
        assert!(!accepts(&t, "b"), "b");
    }

    // --- Multi-codepoint folds ---

    #[test]
    fn fold_trie_sharp_s() {
        // target = ['s','s']
        let t = fold_seq_to_trie(&['s', 's']);
        assert!(accepts(&t, "ss"), "ss");
        assert!(accepts(&t, "sS"), "sS");
        assert!(accepts(&t, "Ss"), "Ss");
        assert!(accepts(&t, "SS"), "SS");
        assert!(accepts(&t, "ß"), "ß U+00DF");
        // ſ folds to ['s'], so ſs should match too
        assert!(accepts(&t, "ſs"), "ſs");
        assert!(accepts(&t, "ſS"), "ſS");
        // single s/S: fold is just ['s'], not ['s','s']
        assert!(!accepts(&t, "s"), "single s");
        assert!(!accepts(&t, "S"), "single S");
    }

    #[test]
    fn fold_trie_fi_ligature() {
        // target = ['f', 'i']  (fold of ﬁ U+FB01)
        let t = fold_seq_to_trie(&['f', 'i']);
        assert!(accepts(&t, "fi"), "fi");
        assert!(accepts(&t, "fI"), "fI");
        assert!(accepts(&t, "Fi"), "Fi");
        assert!(accepts(&t, "FI"), "FI");
        assert!(accepts(&t, "ﬁ"), "ﬁ U+FB01");
        assert!(!accepts(&t, "f"), "incomplete");
        assert!(!accepts(&t, "x"), "x");
    }

    // --- Backward trie ---

    #[test]
    fn fold_trie_back_ascii() {
        let t = fold_seq_to_trie_back(&['s']);
        // advance_back on "xs" from pos 2 should give pos 1
        assert_eq!(t.advance_back(b"xs", 2), Some(1));
        assert_eq!(t.advance_back(b"xS", 2), Some(1));
        let s = "x\u{017F}".to_string();
        assert_eq!(
            t.advance_back(s.as_bytes(), s.len()),
            Some(1),
            "xſ backward"
        );
    }

    #[test]
    fn fold_trie_back_sharp_s() {
        let t = fold_seq_to_trie_back(&['s', 's']);
        // "xss" backward from 3 → 1
        assert_eq!(t.advance_back(b"xss", 3), Some(1));
        // "xß" backward (ß is 2 bytes)
        let s = "x\u{00DF}".to_string();
        assert_eq!(t.advance_back(s.as_bytes(), s.len()), Some(1));
    }

    // --- CharSet → ByteTrie ---
    //
    // In the new design, charset_to_bytetrie only inserts multi-codepoint fold
    // sequences (e.g. ß → "ss").  Single-char case equivalents are handled by
    // CharSet::matches via binary search and do NOT appear in the ByteTrie.

    fn make_ranges_charset(ranges: Vec<(char, char)>) -> CharSet {
        CharSet {
            negate: false,
            ranges,
        }
    }

    /// A charset containing only ß must have the multi-fold sequences in its trie.
    #[test]
    fn charset_trie_sharp_s_multi_fold() {
        let cs = make_ranges_charset(vec![('ß', 'ß')]);
        let t = charset_to_bytetrie(&cs, true);
        // ß and ẞ are inserted by enumerate_inputs(['s','s'])
        assert!(accepts(&t, "ß"), "ß itself (via enumerate_inputs)");
        assert!(accepts(&t, "ẞ"), "ẞ U+1E9E (via enumerate_inputs)");
        assert!(accepts(&t, "ss"), "ss");
        assert!(accepts(&t, "sS"), "sS");
        assert!(accepts(&t, "Ss"), "Ss");
        assert!(accepts(&t, "SS"), "SS");
        // Single 's'/'S' are not fold-sequences of ß — only multi-char "ss"
        assert!(!accepts(&t, "s"), "single s not a multi-char fold");
        assert!(!accepts(&t, "S"), "single S not a multi-char fold");
    }

    /// Capital sharp S (ẞ) has the same multi-fold as ß.
    #[test]
    fn charset_trie_capital_sharp_s_multi_fold() {
        let cs = make_ranges_charset(vec![('\u{1E9E}', '\u{1E9E}')]);
        let t = charset_to_bytetrie(&cs, true);
        assert!(accepts(&t, "ẞ"), "ẞ itself (via enumerate_inputs)");
        assert!(
            accepts(&t, "ß"),
            "ß (same fold class, via enumerate_inputs)"
        );
        assert!(accepts(&t, "ss"), "ss");
        assert!(accepts(&t, "SS"), "SS");
        assert!(!accepts(&t, "s"), "single s");
    }

    /// A range that includes ß must include its multi-fold sequences.
    #[test]
    fn charset_trie_range_includes_sharp_s() {
        // Range ß..=à (U+00DF..=U+00E0)
        let cs = make_ranges_charset(vec![('\u{00DF}', '\u{00E0}')]);
        let t = charset_to_bytetrie(&cs, true);
        assert!(accepts(&t, "ß"), "ß via enumerate_inputs");
        assert!(accepts(&t, "ss"), "ss via ß multi-fold");
        assert!(accepts(&t, "SS"), "SS via ß multi-fold");
        // à (U+00E0) has no multi-char fold → not in ByteTrie
        assert!(!accepts(&t, "à"), "à is a single char, not in ByteTrie");
        assert!(!accepts(&t, "À"), "À is a single char, not in ByteTrie");
    }

    /// A charset with no multi-char fold codepoints produces an empty ByteTrie.
    #[test]
    fn charset_trie_az_no_multi_fold() {
        let cs = make_ranges_charset(vec![('a', 'z')]);
        let t = charset_to_bytetrie(&cs, true);
        // No chars in [a-z] have multi-char folds → trie is empty
        assert!(!accepts(&t, "a"), "a not in multi-fold trie");
        assert!(!accepts(&t, "A"), "A not in multi-fold trie");
        assert!(!accepts(&t, "ſ"), "ſ not in multi-fold trie");
    }
}
