/// Compile-time case-fold expansion utilities.
///
/// `fold_seq_to_trie` builds a [`ByteTrie`] containing every UTF-8 byte
/// sequence that Unicode-case-folds **to** the given target sequence.
/// At match time the engine just walks the trie over raw bytes — no
/// `case_fold()` calls, no UTF-8 decoding.
///
/// `charset_to_bytetrie` builds a [`ByteTrie`] from a `CharSet` by
/// enumerating all matching Unicode codepoints and inserting their UTF-8
/// encodings.
///
/// # Algorithm
///
/// Both functions use the static [`SIMPLE_CASE_FOLDS`] and
/// [`MULTI_CASE_FOLDS`] tables (generated by `scripts/gen_unicode_tables`)
/// instead of scanning all 1.1 M Unicode codepoints at runtime.  Each table
/// has ≈ 1 400 entries — a >700× reduction over the full-codepoint scan.
///
/// For a target sequence `T = [c0, c1, …, cn]` we recursively find all
/// Unicode codepoints `ch` such that `ch.case_fold()` produces some
/// non-empty prefix `T[0..k]`, then recurse on `T[k..]`.  The base case
/// (empty target) inserts the accumulated byte sequence into the output trie.
use crate::bytetrie::ByteTrie;
use crate::vm::CharSet;
use crate::vm::CharSetItem;

// Static tables generated by scripts/gen_unicode_tables from data/CaseFolding.txt.
include!("casefold_data.rs");

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Build a `ByteTrie` containing all UTF-8 byte sequences whose Unicode case
/// fold equals `target`.
///
/// For example, `fold_seq_to_trie(&['s'])` produces a trie accepting
/// `"s"`, `"S"`, `"ſ"` (U+017F), `"ẛ"` (U+1E9B) etc.
///
/// `fold_seq_to_trie(&['s', 's'])` produces a trie accepting `"ss"`, `"sS"`,
/// `"Ss"`, `"SS"`, `"ß"` (U+00DF), combinations with ſ, etc.
pub fn fold_seq_to_trie(target: &[char]) -> ByteTrie {
    let mut trie = ByteTrie::new();
    let mut buf = Vec::new();
    enumerate_inputs(target, &mut buf, &mut trie);
    trie
}

/// Build a *reversed* `ByteTrie` for backward matching (used by
/// `Inst::FoldSeqBack`).
pub fn fold_seq_to_trie_back(target: &[char]) -> ByteTrie {
    fold_seq_to_trie(target).reversed()
}

// ---------------------------------------------------------------------------
// Internal enumeration
// ---------------------------------------------------------------------------

/// Recursively enumerate all input byte sequences that fold to `remaining`,
/// appending discovered bytes to `buf` and inserting complete sequences into
/// `out`.
fn enumerate_inputs(remaining: &[char], buf: &mut Vec<u8>, out: &mut ByteTrie) {
    if remaining.is_empty() {
        out.insert(buf);
        return;
    }

    // Try every split length k (1..=remaining.len()):
    // find all codepoints whose case_fold == remaining[..k], then recurse.
    for k in 1..=remaining.len() {
        let prefix = &remaining[..k];
        let suffix = &remaining[k..];

        for ch in codepoints_with_fold(prefix) {
            let start = buf.len();
            let mut tmp = [0u8; 4];
            let encoded = ch.encode_utf8(&mut tmp);
            buf.extend_from_slice(encoded.as_bytes());
            enumerate_inputs(suffix, buf, out);
            buf.truncate(start);
        }
    }
}

/// Return the simple (single-codepoint) case fold of `ch` using the static
/// table, or `ch` itself if `ch` is a fold fixed-point.
fn simple_fold(ch: char) -> char {
    match SIMPLE_CASE_FOLDS.binary_search_by_key(&ch, |&(s, _)| s) {
        Ok(i) => SIMPLE_CASE_FOLDS[i].1,
        Err(_) => ch,
    }
}

/// Yield all Unicode codepoints whose full case fold equals `target`.
///
/// Uses the static [`SIMPLE_CASE_FOLDS`] / [`MULTI_CASE_FOLDS`] tables
/// instead of scanning 1.1 M codepoints.
fn codepoints_with_fold(target: &[char]) -> Vec<char> {
    if target.len() == 1 {
        let t = target[0];
        let mut result = Vec::new();
        // t itself if it is a fixed point (simple_fold(t) == t).
        if simple_fold(t) == t {
            result.push(t);
        }
        // All src where SIMPLE_CASE_FOLDS[src] == t.
        for &(src, dst) in SIMPLE_CASE_FOLDS {
            if dst == t {
                result.push(src);
            }
        }
        result
    } else {
        // Multi-codepoint target: search MULTI_CASE_FOLDS.
        MULTI_CASE_FOLDS
            .iter()
            .filter(|&&(_, fold)| fold == target)
            .map(|&(src, _)| src)
            .collect()
    }
}

// ---------------------------------------------------------------------------
// CharSet → ByteTrie
// ---------------------------------------------------------------------------

/// Build a `ByteTrie` from a simple (Char/Range-only, non-negated,
/// non-intersecting) `CharSet`.
///
/// With `ignore_case = true` the trie also accepts codepoints that
/// simple-case-fold to a value within the charset, **and** any multi-
/// codepoint byte sequence whose full Unicode case fold matches a codepoint
/// in the charset.  For example, `[ß]` case-insensitively also accepts
/// `"ss"`, `"Ss"`, `"SS"`, `"ẞ"`, etc.
///
/// **Requires** that `charset_is_simple` returns `true` for `cs` (see
/// `vm.rs`).  The caller guarantees `!cs.negate` and `cs.intersections.is_empty()`.
pub fn charset_to_bytetrie(cs: &CharSet, ignore_case: bool, _ascii_range: bool) -> ByteTrie {
    let mut trie = ByteTrie::new();
    let mut buf = [0u8; 4];

    for item in &cs.items {
        match item {
            CharSetItem::Char(c) => {
                if ignore_case {
                    // The effective "folded" value this char contributes.
                    let f = simple_fold(*c);
                    insert_with_reverse_folds(&mut trie, &mut buf, f);
                    // If f has a multi-codepoint full fold (e.g. ß → "ss"),
                    // also accept every byte sequence that folds to that same
                    // sequence (e.g. "ss", "Ss", "SS", "ẞ", …).
                    insert_multi_fold_seqs(&mut trie, f);
                } else {
                    trie.insert(c.encode_utf8(&mut buf).as_bytes());
                }
            }
            CharSetItem::Range(lo, hi) => {
                if ignore_case {
                    let lo_f = simple_fold(*lo);
                    let hi_f = simple_fold(*hi);
                    // Fixed-point chars in [lo_f, hi_f]: their fold is themselves,
                    // so they are accepted.
                    for cp in lo_f as u32..=hi_f as u32 {
                        if let Some(c) = char::from_u32(cp)
                            && simple_fold(c) == c
                        {
                            trie.insert(c.encode_utf8(&mut buf).as_bytes());
                        }
                    }
                    // Source chars whose simple fold lands in [lo_f, hi_f].
                    for &(src, dst) in SIMPLE_CASE_FOLDS {
                        if dst >= lo_f && dst <= hi_f {
                            trie.insert(src.encode_utf8(&mut buf).as_bytes());
                        }
                    }
                    // Chars in [lo_f, hi_f] that have multi-codepoint full folds.
                    // (They are fixed-points for simple_fold so they appear in the
                    // range above, but their fold sequences must also be accepted.)
                    for &(src, fold_seq) in MULTI_CASE_FOLDS {
                        if src >= lo_f && src <= hi_f {
                            insert_multi_fold_seqs_raw(&mut trie, fold_seq);
                        }
                    }
                } else {
                    for cp in *lo as u32..=*hi as u32 {
                        if let Some(c) = char::from_u32(cp) {
                            trie.insert(c.encode_utf8(&mut buf).as_bytes());
                        }
                    }
                }
            }
            _ => unreachable!("charset_is_simple guarantees only Char/Range items"),
        }
    }

    trie
}

/// Insert `f` (if it is a fold fixed-point) and every source codepoint that
/// simple-folds to `f` into `trie`.
fn insert_with_reverse_folds(trie: &mut ByteTrie, buf: &mut [u8; 4], f: char) {
    if simple_fold(f) == f {
        trie.insert(f.encode_utf8(buf).as_bytes());
    }
    for &(src, dst) in SIMPLE_CASE_FOLDS {
        if dst == f {
            trie.insert(src.encode_utf8(buf).as_bytes());
        }
    }
}

/// If `f` has a multi-codepoint full case fold, insert all byte sequences
/// that Unicode-case-fold to that same sequence into `trie`.
fn insert_multi_fold_seqs(trie: &mut ByteTrie, f: char) {
    if let Ok(i) = MULTI_CASE_FOLDS.binary_search_by_key(&f, |&(s, _)| s) {
        insert_multi_fold_seqs_raw(trie, MULTI_CASE_FOLDS[i].1);
    }
}

/// Insert all byte sequences that Unicode-case-fold to `fold_seq` into `trie`.
fn insert_multi_fold_seqs_raw(trie: &mut ByteTrie, fold_seq: &[char]) {
    let mut buf: Vec<u8> = Vec::new();
    enumerate_inputs(fold_seq, &mut buf, trie);
}

/// Build a reversed `ByteTrie` from a `CharSet` (for backward `ClassBack`).
pub fn charset_to_bytetrie_back(cs: &CharSet, ignore_case: bool, ascii_range: bool) -> ByteTrie {
    charset_to_bytetrie(cs, ignore_case, ascii_range).reversed()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn accepts(trie: &ByteTrie, s: &str) -> bool {
        trie.advance(s.as_bytes(), 0) == Some(s.len())
    }

    // --- Single-codepoint folds ---

    #[test]
    fn fold_trie_ascii_s() {
        let t = fold_seq_to_trie(&['s']);
        assert!(accepts(&t, "s"), "s");
        assert!(accepts(&t, "S"), "S");
        assert!(accepts(&t, "ſ"), "ſ U+017F"); // Latin small letter long s (folds to 's')
        assert!(!accepts(&t, "ẛ"), "ẛ U+1E9B folds to ṡ, not s");
        assert!(!accepts(&t, "x"), "x should not match");
        assert!(!accepts(&t, "ß"), "ß has 2-char fold ss, not s");
    }

    #[test]
    fn fold_trie_kelvin() {
        let t = fold_seq_to_trie(&['k']);
        assert!(accepts(&t, "k"), "k");
        assert!(accepts(&t, "K"), "K");
        assert!(accepts(&t, "\u{212A}"), "Kelvin sign U+212A");
        assert!(!accepts(&t, "x"), "x");
    }

    #[test]
    fn fold_trie_ascii_a() {
        let t = fold_seq_to_trie(&['a']);
        assert!(accepts(&t, "a"), "a");
        assert!(accepts(&t, "A"), "A");
        assert!(!accepts(&t, "b"), "b");
    }

    // --- Multi-codepoint folds ---

    #[test]
    fn fold_trie_sharp_s() {
        // target = ['s','s']
        let t = fold_seq_to_trie(&['s', 's']);
        assert!(accepts(&t, "ss"), "ss");
        assert!(accepts(&t, "sS"), "sS");
        assert!(accepts(&t, "Ss"), "Ss");
        assert!(accepts(&t, "SS"), "SS");
        assert!(accepts(&t, "ß"), "ß U+00DF");
        // ſ folds to ['s'], so ſs should match too
        assert!(accepts(&t, "ſs"), "ſs");
        assert!(accepts(&t, "ſS"), "ſS");
        // single s/S: fold is just ['s'], not ['s','s']
        assert!(!accepts(&t, "s"), "single s");
        assert!(!accepts(&t, "S"), "single S");
    }

    #[test]
    fn fold_trie_fi_ligature() {
        // target = ['f', 'i']  (fold of ﬁ U+FB01)
        let t = fold_seq_to_trie(&['f', 'i']);
        assert!(accepts(&t, "fi"), "fi");
        assert!(accepts(&t, "fI"), "fI");
        assert!(accepts(&t, "Fi"), "Fi");
        assert!(accepts(&t, "FI"), "FI");
        assert!(accepts(&t, "ﬁ"), "ﬁ U+FB01");
        assert!(!accepts(&t, "f"), "incomplete");
        assert!(!accepts(&t, "x"), "x");
    }

    // --- Backward trie ---

    #[test]
    fn fold_trie_back_ascii() {
        let t = fold_seq_to_trie_back(&['s']);
        // advance_back on "xs" from pos 2 should give pos 1
        assert_eq!(t.advance_back(b"xs", 2), Some(1));
        assert_eq!(t.advance_back(b"xS", 2), Some(1));
        let s = "x\u{017F}".to_string();
        assert_eq!(
            t.advance_back(s.as_bytes(), s.len()),
            Some(1),
            "xſ backward"
        );
    }

    #[test]
    fn fold_trie_back_sharp_s() {
        let t = fold_seq_to_trie_back(&['s', 's']);
        // "xss" backward from 3 → 1
        assert_eq!(t.advance_back(b"xss", 3), Some(1));
        // "xß" backward (ß is 2 bytes)
        let s = "x\u{00DF}".to_string();
        assert_eq!(t.advance_back(s.as_bytes(), s.len()), Some(1));
    }

    // --- CharSet → ByteTrie ---

    fn make_range_charset(lo: char, hi: char) -> CharSet {
        use crate::vm::CharSetItem;
        let mut cs = CharSet {
            negate: false,
            items: vec![CharSetItem::Range(lo, hi)],
            intersections: vec![],
            ascii_ranges: None,
        };
        cs.compute_ascii_ranges();
        cs
    }

    #[test]
    fn charset_trie_az_case_insensitive() {
        let cs = make_range_charset('a', 'z');
        let t = charset_to_bytetrie(&cs, true, false);
        // ASCII uppercase matched
        assert!(accepts(&t, "A"), "A");
        assert!(accepts(&t, "Z"), "Z");
        assert!(accepts(&t, "a"), "a");
        assert!(accepts(&t, "z"), "z");
        // ſ (U+017F) simple-folds to 's' → should be in class
        assert!(accepts(&t, "ſ"), "ſ U+017F");
        // ß has no simple fold (multi-codepoint) → should NOT be in class
        assert!(
            !accepts(&t, "ß"),
            "ß should not match [a-z] case-insensitive"
        );
        // Kelvin sign (U+212A) folds to 'k'
        assert!(accepts(&t, "\u{212A}"), "Kelvin sign U+212A");
        // digit outside range
        assert!(!accepts(&t, "1"), "digit");
    }

    #[test]
    fn charset_trie_az_case_sensitive() {
        let cs = make_range_charset('a', 'z');
        let t = charset_to_bytetrie(&cs, false, false);
        assert!(accepts(&t, "a"), "a");
        assert!(accepts(&t, "z"), "z");
        assert!(!accepts(&t, "A"), "A case-sensitive");
        assert!(!accepts(&t, "ſ"), "ſ case-sensitive");
    }

    fn make_char_charset(c: char) -> CharSet {
        use crate::vm::CharSetItem;
        let mut cs = CharSet {
            negate: false,
            items: vec![CharSetItem::Char(c)],
            intersections: vec![],
            ascii_ranges: None,
        };
        cs.compute_ascii_ranges();
        cs
    }

    /// `/(?i)[ß]/` must match `ss`, `Ss`, `SS`, `ẞ`, and `ß` itself.
    #[test]
    fn charset_trie_sharp_s_multi_fold() {
        let cs = make_char_charset('ß');
        let t = charset_to_bytetrie(&cs, true, false);
        assert!(accepts(&t, "ß"), "ß itself");
        assert!(accepts(&t, "ẞ"), "ẞ U+1E9E (capital sharp s)");
        assert!(accepts(&t, "ss"), "ss");
        assert!(accepts(&t, "sS"), "sS");
        assert!(accepts(&t, "Ss"), "Ss");
        assert!(accepts(&t, "SS"), "SS");
        assert!(accepts(&t, "ſs"), "ſs (long s + s)");
        assert!(accepts(&t, "ſS"), "ſS");
        // Single 's'/'S' are NOT fold-equivalent to ß
        assert!(!accepts(&t, "s"), "single s");
        assert!(!accepts(&t, "S"), "single S");
    }

    /// `/(?i)[ẞ]/` (capital sharp s) must also match `ss` and `ß`.
    #[test]
    fn charset_trie_capital_sharp_s_multi_fold() {
        let cs = make_char_charset('\u{1E9E}');
        let t = charset_to_bytetrie(&cs, true, false);
        assert!(accepts(&t, "ẞ"), "ẞ itself");
        assert!(accepts(&t, "ß"), "ß (same fold class)");
        assert!(accepts(&t, "ss"), "ss");
        assert!(accepts(&t, "SS"), "SS");
        assert!(!accepts(&t, "s"), "single s");
    }

    /// A range that includes ß must also accept multi-fold sequences.
    #[test]
    fn charset_trie_range_includes_sharp_s() {
        // Range ß..=à (U+00DF..=U+00E0): both bounds are fixed-points for
        // simple_fold, so lo_f=ß, hi_f=à. ß is in the folded range and has
        // a multi-char fold "ss" → the trie must also accept "ss" variants.
        let cs = make_range_charset('\u{00DF}', '\u{00E0}');
        let t = charset_to_bytetrie(&cs, true, false);
        assert!(accepts(&t, "ß"), "ß in range");
        assert!(accepts(&t, "ss"), "ss via ß multi-fold");
        assert!(accepts(&t, "SS"), "SS via ß multi-fold");
        // à is also in the range (simple_fold(à)=à)
        assert!(accepts(&t, "à"), "à in range");
        // À folds to à → also in trie
        assert!(accepts(&t, "À"), "À simple-folds to à");
    }
}
