/// Unicode full case folding at run time.
///
/// Uses the static tables in `crate::data::casefold_data`, pre-generated by
/// `scripts/gen_unicode_tables` from `data/CaseFolding.txt`.
/// Implements *full* case folding (status C and F entries), which may expand
/// a single codepoint to a sequence of codepoints (e.g. ß → ['s','s']).
use crate::data::casefold_data::{MULTI_CASE_FOLDS, SIMPLE_CASE_FOLDS};

/// The result of fully case-folding a single character.
///
/// `Single` covers the common case (one output codepoint) without heap allocation.
/// `Multi` holds the sequence for the rare multi-codepoint folds (e.g. ß → ss).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CaseFold {
    /// Identity or single-codepoint fold.
    Single(char),
    /// Multi-codepoint fold (e.g. ß → ['s','s']).
    Multi(&'static [char]),
}

impl CaseFold {
    /// Iterate over the folded codepoints.
    pub fn chars(&self) -> &[char] {
        match self {
            CaseFold::Single(c) => std::slice::from_ref(c),
            CaseFold::Multi(cs) => cs,
        }
    }
}

/// Return the full Unicode case fold of `ch`.
///
/// - If `ch` has a multi-codepoint fold (e.g. ß → `['s','s']`), returns
///   `CaseFold::Multi`.
/// - If `ch` has a single-codepoint fold, returns `CaseFold::Single(folded)`.
/// - If `ch` has no non-trivial fold (i.e. it is already folded), returns
///   `CaseFold::Single(ch)`.
#[inline]
pub fn case_fold(ch: char) -> CaseFold {
    // Check multi-codepoint folds first (small table, ~104 entries).
    if let Ok(i) = MULTI_CASE_FOLDS.binary_search_by_key(&ch, |&(src, _)| src) {
        return CaseFold::Multi(MULTI_CASE_FOLDS[i].1);
    }
    // Check single-codepoint folds (~1,300 entries).
    if let Ok(i) = SIMPLE_CASE_FOLDS.binary_search_by_key(&ch, |&(src, _)| src) {
        return CaseFold::Single(SIMPLE_CASE_FOLDS[i].1);
    }
    // Identity.
    CaseFold::Single(ch)
}

/// Iterator adapter: yields the full case-fold sequence of each character in a string.
///
/// Equivalent to `s.chars().flat_map(case_fold_chars)` but works with `CaseFold`.
#[allow(dead_code)]
pub struct CaseFoldIter {
    inner: std::str::Chars<'static>,
    buf: Option<CaseFold>,
    buf_pos: usize,
}

/// Convenience: iterate over the folded chars of a `&'static str`.
/// For short patterns this is zero-alloc.
impl Iterator for CaseFoldIter {
    type Item = char;
    fn next(&mut self) -> Option<char> {
        loop {
            if let Some(ref fold) = self.buf {
                let chars = fold.chars();
                if self.buf_pos < chars.len() {
                    let c = chars[self.buf_pos];
                    self.buf_pos += 1;
                    return Some(c);
                }
                self.buf = None;
                self.buf_pos = 0;
            }
            let next_ch = self.inner.next()?;
            self.buf = Some(case_fold(next_ch));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fold_identity() {
        assert_eq!(case_fold('a'), CaseFold::Single('a'));
        assert_eq!(case_fold('z'), CaseFold::Single('z'));
    }

    #[test]
    fn fold_simple() {
        assert_eq!(case_fold('A'), CaseFold::Single('a'));
        assert_eq!(case_fold('Z'), CaseFold::Single('z'));
    }

    #[test]
    fn fold_multi_sharp_s() {
        assert_eq!(case_fold('ß'), CaseFold::Multi(&['s', 's']));
    }

    #[test]
    fn fold_kelvin() {
        assert_eq!(case_fold('\u{212A}'), CaseFold::Single('k'));
    }
}
